# Generated by Django 4.2.2 on 2023-10-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_stock_product_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
