# Generated by Django 4.2.2 on 2023-11-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_minimum_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
