# Generated by Django 4.2.2 on 2023-12-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_minimum_stock'),
        ('products', '0005_alter_stock_current_quantity'),
    ]

    operations = [
    ]
