# Generated by Django 4.2.2 on 2023-11-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_minimum_stock'),
        ('sales', '0003_remove_sale_product_alter_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(related_name='sale_products', to='products.product'),
        ),
    ]
