# Generated by Django 4.2.2 on 2023-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_product_alter_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='departament',
            field=models.CharField(choices=[('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Santa Cruz', 'Santa Cruz'), ('Oruro', 'Oruro'), ('Potosi', 'Potosi'), ('Tarija', 'Tarija'), ('Beni', 'Beni'), ('Pando', 'Pando'), ('Chuquisaca', 'Chuquisaca')], max_length=12),
        ),
    ]
