# Generated by Django 4.2.2 on 2023-10-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_shipment_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
