# Generated by Django 4.2.2 on 2023-12-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_product'),
        ('sales', '0005_alter_saledetail_created_at_and_more'),
    ]

    operations = [
    ]
