# Generated by Django 4.2.2 on 2024-01-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clients',
            managers=[
            ],
        ),
    ]
